### ISSUE TITLE
Offline usage doesn't work after closing and reopening Obsidian

### ISSUE THREAD

**Issue by desk7** [Nigecat/obsidian-desmos#88]
**Describe the bug**
- I render the first graph while connected to internet
- I go offline
- New graphs are correctly rendered
- I close and reopen Obsidian
- Old graphs are not rendered anymore. No errors, only blank space instead of the graph

**Expected behavior**
Graphs should be always correctly rendered.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: 1.1.16
 - Plugin Version: 0.6.4

**Comment by Nigecat** [comment]
This seems to have broken after an update from v1.5 to v1.6 of the Desmos API.
It seems like versions >1.5 require an internet connection to function since the calculator itself starts to give network errors.
I'll probably just add a toggle to use the older version in the settings for now, usable if you don't need any of the newer features.
